lichess-org/mobile

android/app/src/debug/AndroidManifest.xml
lib/src/features/auth/data/auth_repository.dart

In concert with the following command (which must be run after the emulator/device has started): adb reverse tcp:9663 tcp:9663
Avoid 10.0.2.x networking as it will confuse CORS.  Use localhost:9663
If Chrome instacrashes, it is likely you need to disable vulkan in  emulator settings.  Will add docs for all this pending discussion of where they should go.

allow http on android devices/emulators

---

.gitignore

We need to skip intelliJ generated files in .gitignore.

Skip intelliJ files in .gitignore

---

lib/src/ui/puzzle/puzzle_dashboard_screen.dart

Makes sure the "Puzzle themes" text is bolded/styled like in the other buttons.
| Before | After |
| --- | --- |
| ![image](https://github.com/lichess-org/mobile/assets/10077686/fec2d293-229a-405b-bf40-2eb91291c5d6) | ![image](https://github.com/lichess-org/mobile/assets/10077686/c6e5a3e2-b132-409b-a2bd-83526238e8db) |

Set puzzle themes text style

---

lib/src/view/settings/board_theme_screen.dart

Settings: Board theme screen had incorrect title

---

ios/Runner/Info.plist
lib/src/model/common/speed.dart
lib/src/model/common/time_increment.dart
lib/src/view/play/time_control_modal.dart

Fix the logic used to determine speed from a time control. Now increments are taken into account and 0+1 is now correctly shown as "bullet".
Remove the ultrabullet section from the fast pairing time control modal because ultrabullet has only one option possible.
Closes #259

Fix 0+1 shown as ultrabullet in time control selector

---

lib/src/view/user/countries.dart

Related to [lila/pull/13605](https://github.com/lichess-org/lila/pull/13605). The crossmatch here gave an additional country: Zimbabwe, which I suspect to have been omitted by accident, for it is at the end of the list.

add flags of Netherlands Antilles, Canary Islands, Zimbabwe

---

lib/src/model/analysis/analysis_controller.dart
lib/src/view/analysis/analysis_screen.dart

Fixes #471
I've modified the graph such that it is clickable. It solely depends on the x-value of the touch input. Maybe there is more sophisticated method that involves the distance on the y -axis that works better. 
However I observed that the website implementation also considers only the x-value.
Also I changed the graph type to be non-curved. The current curved representation sometimes leads to the maximum not being on a move itself.
To illustrate the difference, please refer to the following videos:
<details>
<summary>isCurved: true</summary>
https://github.com/lichess-org/mobile/assets/78898963/de35e001-213c-4b22-b543-cf5fd30b8361
</details>
<details>
<summary>isCurved: false</summary>
https://github.com/lichess-org/mobile/assets/78898963/0fc200ca-3e25-40f1-ad83-c1a9acd154b6 …

Clickable AcplChart 

---

lib/src/view/analysis/tree_view.dart

Change the color of the mainline, so that it is more visible and the notation looks better organized:
<details>
<summary>Old</summary>
</details>
<details>
<summary>New</summary>
</details>

improve visibility of mainline in treeview

---

lib/main.dart
lib/src/constants.dart
lib/src/view/analysis/analysis_screen.dart
lib/src/view/puzzle/history_boards.dart
lib/src/view/puzzle/puzzle_history_screen.dart
lib/src/widgets/board_table.dart

Closes #426
replacing `kTabletThreshold` with `FormFactor.tablet` and `getScreenType(context)`
It updates the following files:
-   lib/main.dart
-   lib/src/constants.dart
-   lib/src/view/analysis/analysis_screen.dart
-   lib/src/view/puzzle/history_boards.dart
-   lib/src/view/puzzle/puzzle_history_screen.dart
-   lib/src/widgets/board_table.dart

Remove kTabletThreshold constant 

---

lib/src/utils/string.dart

In the german version the translation of “Blunders” to “Grobe Patzer” had a minor bug in the analysis screen. The word “Patzer” was written in lowercase. I have modified the capitalize method to ensure that only the first letter of string is capitalized. Now "grobe Patzer" is correctly capitalized to "Grobe Patzer". For other languages this should not make a difference.

correct capitalization

---

lib/src/utils/string.dart
lib/src/view/puzzle/puzzle_dashboard_widget.dart
lib/src/view/puzzle/puzzle_feedback_widget.dart
lib/src/view/puzzle/puzzle_tab_screen.dart
lib/src/view/user/perf_stats_screen.dart

closes #504
I added localizations to integers that are likely to be larger than 1000 (number of games played and also the number of times a puzzle has been played), except ratings. It could be easily extended to more numbers. 
Tested for German, French, and English.

localize numbers

---

lib/src/navigation.dart
lib/src/utils/focus_detector.dart
lib/src/utils/immersive_mode.dart
lib/src/view/game/game_body.dart
lib/src/view/game/lobby_screen.dart
lib/src/view/game/standalone_game_screen.dart
lib/src/view/home/home_tab_screen.dart
lib/src/view/puzzle/puzzle_screen.dart
lib/src/view/puzzle/storm_screen.dart
lib/src/view/puzzle/streak_screen.dart
lib/src/view/relation/relation_screen.dart
lib/src/view/watch/live_tv_channels_screen.dart
lib/src/view/watch/tv_screen.dart
lib/src/view/watch/watch_tab_screen.dart
pubspec.lock
pubspec.yaml
test/test_app.dart

So far we've been relying on `RouterObserver` and `RouteAware` widgets to react to screen changes but this solution had flaws. 
In this PR we're replacing it with a `FocusDetector` based solution, much more robust.
- Immersive mode should now behave properly (allowing android back swipe gesture on screens pushed above a board screen)
- No more issues with root navigator vs navigator to detect screen changes
- Future proof with coming deep links when we need to ensure a websocket connection is created again when a hidden screen gets visibility back

Focus detector and immersive mode improvements

---

lib/src/model/user/profile.dart
lib/src/view/account/edit_profile_screen.dart
lib/src/view/user/user_profile.dart

Fixes some nasty bugs in the profile screen:
- Currently, social media links without https or http couldn't be parsed due to the URI standard 
- I removed empty links
- All profile text was displayed on a single line and consequently often cut off. I set the maximum to ten lines.  Also it replaces all new lines with a space as its done on the website.
- An error message with no explanation appeared when entering whitespace strings in profile editing. This fix trims leading and trailing whitespace to prevent the error. 
<details>
<summary>before</summary>
</details>
<details>
<summary>after</summary>
</details>

Fix Bugs in Profile Screen

---

lib/src/view/user/perf_stats_screen.dart

closes #566
currently the UserPerfStats has two problems
1. displays [USERNAME] is better than 0.00% of [`perfType`] players. when` perf.percentile == 0.0`
2. displays ? in Rank Card for perfs with no leaderboard (i.e. correspondance)
proposed fix
1. display AreBetterThanPercentOfPerfTypePlayers when `perf.percentile > 0.0`.
2. remove rank `StatCard` for correspondence perf.
**maintainer input needed**
when removing rank stat card visually going from 2×2 grid layout to 1 then 2×1  isn't pleasing is it okay if we leave it as is or should we remove rows all together (for correspondence )  to display progress, rating deviation ,highest Elo and lowest Elo on a single row
in short
the original is
| Progress    |            |
| ----------- | ---------- |
| rank        | deviation  |
| highest …

Remove Inapplicable Correspondence Statistics 

---

lib/src/view/user/countries.dart

Country named Turkey before officially changed its name to Turkiye.
Some related news and sources for confirmation:
https://www.un.org/en/about-us/member-states/turkiye
https://turkiye.un.org/en/184798-turkeys-name-changed-t%C3%BCrkiye
https://www.theguardian.com/world/2022/jun/03/turkey-changes-name-to-turkiye-as-other-name-is-for-the-birds

Country name Turkey officially changed to Turkiye

---

lib/src/view/user/user_profile.dart

fixes bug reported on discord that for certain languages not the complete text was displayed on accounts that violated tos.

wrap around tos violation

---

lib/src/view/engine/engine_gauge.dart
lib/src/view/play/time_control_modal.dart
lib/src/view/puzzle/puzzle_dashboard_widget.dart
lib/src/widgets/board_table.dart
lib/src/widgets/feedback.dart

I fixed the deprecated warnings that appear when running `flutter analyze`. The `background` and `onBackground` were easily replaced with `surface` and `onSurface` without any visible changes. The suggested replacement for `surfaceVariant` did not work; the best I could come up with is `tertiary.withOpacity(0.15)`, and it looks similar to before now.
It changes the color of the tiles with the timecontrols.
I tested it with light, dark, and system colors and different themes, and it looks pretty good.
| New                                            | Old                                            |
|------------------------------------------------|------------------------------------------------|
| ![Image 1](https://github.com/lichess-org/mobile/assets/78898963/41b772cb-2145-4ed8-ba44-d09 …

Fix deprecated warnings for some colorSchemes properties

---

lib/src/model/common/node.dart
pubspec.lock
pubspec.yaml
test/model/common/node_test.dart

fix alternative castling

---

lib/src/view/analysis/tree_view.dart

The move number was not displayed if it's Black's turn to move in the initial position of the analysis.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>

fixes the notation if the analysis starts with black to move

---

lib/src/view/analysis/analysis_position_choice_screen.dart

The user will now be able to import a PGN file even if it does not contain any moves. This functionality is already present in the old app and on the website. For instance:
```
[Variant "From Position"]
[FEN "r1bqkb1r/pppp1ppp/2n2n2/4p2Q/2B1P3/8/PPPP1PPP/RNB1K1NR w KQkq - 0 1"]
```
This position can now be analysed. One advantage of this over plain FEN is that PGN headers can also be imported. 
I let the previous behaviour unchanged: If moves are present, at least the first move must be legal for the PGN analysable.
If there are no moves, there has to be a FEN header for it to be analysable.

Parse pgn without moves

---

lib/src/view/account/edit_profile_screen.dart

Updates the minimum FIDE Elo, which was recently changed. On the server side this change is already implemented and entering a number between 1000 and 1400 lead to strange behavior.
The corresponding lila PR: https://github.com/lichess-org/lila/pull/14779

update min fide elo

---

lib/src/model/puzzle/puzzle_providers.dart
lib/src/view/puzzle/storm_dashboard.dart
lib/src/view/puzzle/storm_screen.dart
lib/src/view/user/perf_cards.dart
lib/src/view/user/perf_stats_screen.dart

This PR resolves the issue of displaying other users storm highscores. At the moment users would either be directed to their own highscore screen or encounter an error if not logged in. 
Now it should correctly display the highscores of other users. Also, I have included the user's name in the screen title, as it's now possible to view highscores of other users.
<details>
<summary>Preview</summary>
</details>
I can not test it for iOS but I copied the code from perf_stats_screen.
One question remaining is whether we really should implement caching for the storm dashboard. Currently, if a user views their history, plays, beats their daily highscore and then revisits their history, the updated highscore isn't displayed.

Fix Storm Dashboard for Other Users

---

lib/src/view/analysis/analysis_screen.dart
pubspec.lock
pubspec.yaml

Display text vertically for game phases

---

.github/dependabot.yml

Groups all CI action version updates to one PR. Follow same weekly schedule as Dart/Pub updates.

Dependabot: add updates for Github Action workflows

---

lib/src/model/puzzle/puzzle_controller.dart
lib/src/model/puzzle/puzzle_theme.dart
lib/src/view/puzzle/puzzle_screen.dart
lib/src/view/puzzle/streak_screen.dart

Implements #595: Allows the user to analyze the last puzzle (the one they failed) of the streak or normal puzzles on the analysis board. For streak, there is a button in the bottom bar. For normal puzzles I merged it together with the share puzzle to a menu, because we should not have two separate buttons for analysis (evaluation bar and analysis board) in the same button bar.
When the user presses to go to the analysis board the initial position corresponds to the starting position of the puzzle and the moves of the solution are there.

puzzle(-streak) analysis in analysisboard

---

lib/src/model/puzzle/puzzle_providers.dart
lib/src/model/puzzle/puzzle_repository.dart
lib/src/model/puzzle/puzzle_streak.dart
lib/src/model/puzzle/storm_controller.dart
lib/src/view/puzzle/storm_screen.dart
lib/src/view/puzzle/streak_screen.dart
test/view/puzzle/storm_screen_test.dart

Close https://github.com/lichess-org/mobile/issues/633 and https://github.com/lichess-org/mobile/issues/646

Fix puzzle storm and streak issue with invalidating provider

---

lib/src/model/analysis/analysis_controller.dart
lib/src/view/analysis/analysis_screen.dart

For a game that doesn't start from move 1 the ACPL chart and the analysis screen current move will be offset by the index of the first move of the game.

Change index for analysis that doesn't start from chess initial position

---

README.md

Updated README with instructions for using Lichess dev server and added a note regarding URL scheme changes in the recent code.

docs: Add instructions for using Lichess dev server in README

---

lib/src/model/common/eval.dart
lib/src/model/engine/uci_protocol.dart

This ensures that we emit an evaluation from `UCIProtocol` once checkmate or stalemate has been reached, addressing https://github.com/lichess-org/mobile/issues/717.
Stockfish sends the message `info depth 0 score mate 0` when checkmate is reached and `info depth 0 score cp 0` when stalemate is reached. Before this change, these messages were being filtered out (by an explicit check for checkmate and because `nodes` and `time` were missing for stalemate), so no evaluation was emitted. This led to the analysis board retaining a stale list of "best moves" and suggesting nonsense.
An alternative approach would be to allow for the stale "best moves" list, and just hide the arrows if the game is over. I prefer the approach taken in this PR, however, because it respects Stockfish as the source …

Clear engine suggestion arrows after reaching checkmate or stalemate

---

android/app/build.gradle
android/app/src/debug/AndroidManifest.xml
android/app/src/debug/google-services.json

- Change the application ID of the debug build on Android from `org.lichess.mobileV2` to `org.lichess.mobileV2.debug`, so it is possible to have both installed at the same time
- Rename the app from "Lichess beta" to "Lichess - DEBUG", so it is easy to tell which version is which
The Android emulator performs poorly on my computer, so I have been using my personal phone to test changes. With this change, I will no longer have to uninstall the production app from the Play Store in order to develop.
Initial testing:
- Installed "Lichess beta" from the Play Store
- Installed the debug build via `flutter run --dart-define=LICHESS_HOST=lichess.dev --dart-define=LICHESS_WS_HOST=socket.lichess.dev`
- Verified that both builds are installed
- Verified that the debug build is named "Lichess - …

Make it possible to install Play Store and debug builds on the same device

---

android/app/src/main/AndroidManifest.xml
android/app/src/main/kotlin/org/lichess/mobileV2/MainActivity.kt
android/app/src/main/res/xml/backup_rules.xml
lib/src/app.dart
lib/src/app_initialization.dart
lib/src/db/database.dart
lib/src/db/secure_storage.dart
lib/src/db/shared_preferences.dart
lib/src/model/auth/auth_session.dart
lib/src/model/common/service/sound_service.dart
lib/src/model/common/socket.dart
lib/src/model/engine/evaluation_service.dart
lib/src/utils/android.dart
lib/src/utils/device_info.dart
lib/src/utils/package_info.dart
test/test_app.dart
test/test_container.dart

Related issue: #736 
Changes in this PR:
- configure flutter secure storage with `EncryptedSharedPreferences`
- exclude secure storage from app backup
- catch exception when reading secure data fails in app initialisation
- add an error screen inviting the user to clear app data when it fails to load (as last resort)

Attempt to fix secure storage crash after app reinstall on Android

---

android/app/build.gradle

The [Dependency Info Block](https://developer.android.com/build/dependencies#dependency-info-play) is an encrypted proprietary blob from Google that is added to every APK and AAB file by default, and that is [not reproducible](https://issuetracker.google.com/issues/268071369).
As discussed in #743, this pull request [removes](https://developer.android.com/reference/tools/gradle-api/8.4/com/android/build/api/dsl/DependenciesInfo) this blob from APK files by adding the following in [build.gradle](android/app/build.gradle):
```java
android {
…
dependenciesInfo {
includeInApk false    # APK files
includeInBundle true  # AAB files
}
}
```
This pull request does not remove the Dependency Info Block from AAB files because, at the moment, those files are not shared with anyone else than the …

Remove Dependency Info Block

---

lib/src/view/puzzle/storm_screen.dart

In English, these strings are something like "End run (hotkey: ...)" and "New run (hotkey: ...)". The previous logic discarded the text in parenthesis by simply keeping the first two words.
However, in some languages we may have more than two words (e.g. in German it's "Beende den Run"). With this change, we keep everything until the '(' character, which should be more robust.
If the string for some reason does not contain '(' at all, split('(') will return a list containing the string itself, so that will work too.

fix text being cut off in stormNewRun and stormEndRun translations

---

lib/src/model/challenge/challenge.dart
lib/src/view/play/challenge_screen.dart

implements #797
closes #803
Adds the possibility to challenge another player with a fen:
Behavior with an invalid fen: 
https://github.com/lichess-org/mobile/assets/78898963/a156e151-48af-4638-bc00-7548ea156520
Behavior with a valid fen:
https://github.com/lichess-org/mobile/assets/78898963/57f585cc-be6b-4182-b3d7-d968cbf16af4
Some remarks:
- From position games can not be rated, so the button is disabled
- The last position used to challenge is not stored (in my opinion this is not necessary)
- Assumes that the fen checker is the same as employed on the serverside, otherwise it might lead to strange behavior.
- Was not tested on iOS

Challenge from a Position with Fen

---

docs/internationalisation.md
translation/source/mobile.xml

This adresses most of the feedback I've seen on crowdin about the new mobile-only texts

Extend translation comments based on crowdin feedback

---

lib/src/model/common/eval.dart
lib/src/view/analysis/analysis_screen.dart
pubspec.lock
pubspec.yaml

- Not sure if we still need the different opacities now...? The old app does not have them, but I think it looks nice. The Web UI seems to use a different opacity for the best move, and the same opacity for all other moves
- Scaling logic could probably be adjusted in the feature based on user feedback, but I think the result looks pretty close to the old app and the web UI already.

feat: scale arrows in analysis based on winning chances

---

lib/src/model/puzzle/puzzle_controller.dart
lib/src/view/puzzle/puzzle_screen.dart
lib/src/widgets/bottom_bar_button.dart
test/view/puzzle/puzzle_screen_test.dart

close #761 
This alters the "show solution button" to only show the next move in the solution, which is in line with both the website and the old app.

only show next correct move when viewing puzzle solution

---

docs/setting_dev_env.md

lila-docker runs on 8080 by default, so the port forwarding commands are a bit different

docs: add lila-docker instructions to settings_dev_env.md

---

lib/src/view/game/game_body.dart
lib/src/widgets/board_table.dart

This is consistent with both the old app and the Web UI

feat: hide move list in zen mode

---

lib/src/model/settings/board_preferences.dart
lib/src/view/analysis/analysis_screen.dart
lib/src/view/settings/board_behavior_settings_screen.dart
lib/src/view/settings/piece_shift_method_settings_screen.dart
lib/src/widgets/board_preview.dart
lib/src/widgets/board_table.dart
lib/src/widgets/board_thumbnail.dart
pubspec.lock
pubspec.yaml

Closes #855
Needs https://github.com/lichess-org/flutter-chessground/pull/39

feat: support changing input method in settings (tap+drag, tag, drag)

---

lib/src/view/puzzle/dashboard_screen.dart

I used the desktop formfactor because it only affects tablets in landscape mode.
before:
after:

fix: change puzzle dashboard graph size on tablet, to prevent overflow

---

lib/src/model/analysis/analysis_controller.dart

fixes #870 
sounds should now be played correctly when user goes to previous or next move on analysis board. The issue was that only associated move of current node (after the requested change) was considered when determining which sound to play. Now the associated move of current node is used when user moves forward through the tree and associated move of previous node (before the requested change) is used when backtracking.
This also fixes move sound not playing when reverting first move of the game. Now the normal move sound is played whenever current node is not a Branch. I am not sure about this, so I am looking for some feedback if this is undesired behavior.

fix incorrect move sounds during analysis

---

lib/src/view/watch/watch_tab_screen.dart

The previous code would hide the `_BroadcastWidget` widget by returning `SizedBox.shrink()`, but that would still create an empty grid space in landscape mode.
To fix this, factor out the widget list into a getter (to avoid code duplication) and comment out the `_BroadcastWidget` in that list for now.
Fixes #829

fix: empty space in "Watch" tab in landscape orientation

---

lib/src/view/home/home_tab_screen.dart

Closes #915
[editing.webm](https://github.com/user-attachments/assets/d781a7d8-1fa1-4fc7-9f08-bb7e43924f6a)

fix: ignore pointer events when editing widgets

---

lib/src/view/clock/clock_screen.dart

This is just a suggestion but I think drawing edge to edge on the clock screen makes things look nicer on both Android and iOS.
<details>
<summary>iOS Screenshots</summary>
| Before  | After |
| ------------- | ------------- |
|![ios_before](https://github.com/user-attachments/assets/1e97c0b2-4403-4cb7-abbb-d3a49fefb00a)  | ![ios_after](https://github.com/user-attachments/assets/41f54978-ef78-47fd-ab51-65d2baa3d3db)
</details>
<details>
<summary>Android Screenshots</summary>
| Before  | After |
| ------------- | ------------- |
| ![android_before](https://github.com/user-attachments/assets/4f0f9d51-d46f-485e-80ba-0c908eaa6e49) | ![android_after](https://github.com/user-attachments/assets/6ff58f63-1800-43ef-92fc-59cf6e286953)
</details>

Suggestion: Draw clock edge to edge

---

lib/src/view/analysis/analysis_screen.dart
lib/src/view/board_editor/board_editor_screen.dart
lib/src/view/correspondence/offline_correspondence_game_screen.dart
lib/src/view/game/archived_game_screen.dart
lib/src/view/game/game_body.dart
lib/src/view/game/game_loading_board.dart
lib/src/view/opening_explorer/opening_explorer_screen.dart
lib/src/view/puzzle/puzzle_screen.dart
lib/src/view/puzzle/storm_screen.dart
lib/src/view/puzzle/streak_screen.dart
lib/src/view/watch/tv_screen.dart
lib/src/widgets/bottom_bar.dart

This gets rid of a lot of code duplication and makes it more straight-forward to build new screens for new features.
Note that the Row in BottomBar now has MainAxisAlignment.spaceAround by default, so it's not necessary anymore to wrap buttons in `Expanded`.

refactor: add common widget for BottomBar

---

lib/src/model/game/archived_game.dart
lib/src/model/game/game.dart
lib/src/view/game/game_player.dart

Improves the display of master games opened from the masters database in the opening explorer:
- The rating is now parsed (f.ex Carlsen, M. (2882) gets split up) and saved in the rating field.
- The offline icon is no longer shown as it doesn’t apply to master games.
- When opening a game from the database, then viewing it in the analysis board and sharing it as a PGN, the player names and ratings are now included in the PGN.
| **Before** | **After** |
|------------|-----------|
| ![Screenshot_20240901-144106](https://github.com/user-attachments/assets/2ae872c5-f22a-4611-9671-8c63eb83c62e) | ![Screenshot_20240901-144012](https://github.com/user-attachments/assets/7f6e719e-eb5b-4d50-958e-85f6a4014ba7) |
| ![Screenshot_20240901-144117](https://github.com/user-attachments/assets/bdd0cb49-7a0b …

improve display and sharing of master games

---

lib/src/view/game/game_body.dart
lib/src/view/puzzle/storm_screen.dart
lib/src/view/puzzle/streak_screen.dart
lib/src/widgets/platform_alert_dialog.dart
lib/src/widgets/yes_no_dialog.dart

In a similar spirit to `PlatformScaffold`, but implementation was much more straight-forward. So I think one screenshot is enough:

refactor: add PlatformAlertDialog

---

lib/src/model/clock/clock_controller.dart
lib/src/view/clock/clock_settings.dart
lib/src/view/home/quick_game_button.dart
lib/src/view/play/create_custom_time_control_screen.dart
lib/src/view/play/time_control_modal.dart

Time handicap in clock tool

---

lib/src/model/common/node.dart
test/model/common/node_test.dart

Fix #983: Implements logic to avoid converting the castling move when the rook is on the same square, along with a test case to prevent similar issues in the future.

fix castling in 960

---

lib/src/view/analysis/analysis_share_screen.dart

fix #948 
This pull request improves the sharing of PGNs:
- The values of entered text are now saved automatically, so the user doesn't need to submit to save the text.
- Submitting a field automatically jumps to the next one and selects all text. If the next field is the "Result" field, a choice picker will appear.
- Tapping on a field automatically selects all the text.
https://github.com/user-attachments/assets/4b33655a-6684-4d24-a47f-569b50a15b6b
Remarks:
- not tested on iOS

Improve share pgn

---

lib/src/model/analysis/analysis_controller.dart
lib/src/model/opening_explorer/opening_explorer_repository.dart
lib/src/view/opening_explorer/opening_explorer_screen.dart
test/view/opening_explorer/opening_explorer_screen_test.dart

The name of the opening in the opening explorer now links to pages in https://lichess.org/opening/ instead of in https://en.wikibooks.org/wiki/Chess_Opening_Theory/.
Discussed recently in #836.

feat: link opening name to lichess page instead of wikibooks in explorer

---

lib/src/model/coordinate_training/coordinate_training_controller.dart
lib/src/model/coordinate_training/coordinate_training_preferences.dart
lib/src/view/coordinate_training/coordinate_display.dart
lib/src/view/coordinate_training/coordinate_training_screen.dart
lib/src/view/tools/tools_tab_screen.dart
test/view/coordinate_training/coordinate_training_screen_test.dart

I think it makes sense to use the new ChessboardEditor widget here as well, since we can reuse the onEditedSquare callback to get notified when the user taps a square. With the normal Chessboard widget, this is currently not implemented, we only have callback when a (legal) move is made.
Haven't done any work on this yet, just opening the draft to let people know I'll start working on this next.

feat: coordinate trainer

---

lib/src/widgets/user_full_name.dart

We'll want to hide the user flair in the study list screen to save space (the website and old app also do this)

[Study] feat: allow hiding flair in UserFullNameWidget

---

.fvm/fvm_config.json
.fvmrc
.gitignore
docs/internationalisation.md
docs/setting_dev_env.md

Hello again 🙂
FVM 3.x is available as of 2024-02-19, so it seems it's probably been enough time for folks to upgrade. As described in the [changelog](https://github.com/leoafarias/fvm/blob/main/CHANGELOG.md#breaking-changes), `.fvmrc` is the new config file; `.fvm/fvm_config.json` is now a legacy file.
So this PR is just a bit of tidying to upgrade to FVM 3.0+. Looking forward to your feedback!

🧹  Update FVM config files for FVM 3.0

---

lib/src/view/board_editor/board_editor_screen.dart

Implements a partial fix for #1005

[BoardAnalysis] disable board analysis if more than 32 pieces on board

---

lib/src/view/watch/tv_screen.dart

~~Fixes #1026~~
feat: add last move highlights in TV
Created and passed `GameData` to display last move highlights and checks.

fix: [TV] add last move highlights

---

lib/src/model/analysis/analysis_controller.dart
lib/src/model/common/node.dart
lib/src/model/common/uci.dart
lib/src/view/analysis/tree_view.dart
test/view/analysis/analysis_screen_test.dart

Especially for heavily commented PGNs this is now much more readable. We're also more consistent with the website now. I added screenhots for comparison below.
I know this is a rather big refactoring, and the recursive nature of this stuff is quite complex, so let me know if anything is unclear. 
I also made a few style adaptions to be a bit more consistent with the the Web UI, but I don't have any strong opinions here, feel free to tweak the styling again after merging.
(Left: Before, Right: This PR)
<p float="left">
</p>
lichess.org for comparison:

feat: make analysis tree view more "tree like"

---

lib/main.dart
lib/src/init.dart
lib/src/model/auth/auth_controller.dart
lib/src/model/settings/board_preferences.dart
lib/src/utils/chessboard.dart
lib/src/view/puzzle/puzzle_feedback_widget.dart
lib/src/view/settings/piece_set_screen.dart
pubspec.lock
pubspec.yaml
test/model/auth/auth_controller_test.dart

The goal is to bypass the default flutter `ImageCache` and `Image` widgets which can lead to unexpected reloading of images, causing a "blink" effect.
Closes #236 
Probably fixes #1055 (I could not reproduce to ensure it)
Probably fixes #1027 
Incidentally fixes a failing test in `auth_controller_test.dart` that aroused in CI at the time of this PR.

Use a global cache to preload chess pieces

---

lib/src/model/study/study_list_paginator.dart
lib/src/model/study/study_repository.dart
lib/src/view/study/study_list_screen.dart
lib/src/view/study/study_screen.dart
lib/src/view/tools/tools_tab_screen.dart
lib/src/view/user/player_screen.dart
lib/src/view/user/search_screen.dart
lib/src/widgets/platform_search_bar.dart
test/view/study/study_list_screen_test.dart

@veloce Since studies are such a huge feature, I'd suggest we split it up and start with this PR that only will add the study list screen. This also makes it easier for others to take over development from me if necessary. After review, we can hide the button until the study feature is fully implemented.

feat: add study list screen

---

lib/src/model/analysis/analysis_controller.dart
lib/src/widgets/pgn.dart
test/view/analysis/analysis_screen_test.dart

[expand.webm](https://github.com/user-attachments/assets/0d39f689-e8a7-4b5f-81f5-d3e183dcf024)

feat: add button to expand collapsed variations

---

lib/src/model/analysis/analysis_controller.dart
lib/src/model/settings/preferences_storage.dart
lib/src/model/study/study_controller.dart
lib/src/model/study/study_preferences.dart
lib/src/view/study/study_bottom_bar.dart
lib/src/view/study/study_screen.dart
lib/src/view/study/study_settings.dart
lib/src/view/study/study_tree_view.dart
lib/src/view/tools/tools_tab_screen.dart
test/view/analysis/analysis_screen_test.dart
test/view/study/study_screen_test.dart

Feature set is the same as the old app for now, I'll add support for interactive studies in another PR.
Chat is also missing for now, I'll have to figure out how to use the websocket for that.
@veloce The build fails because this PR depends on some of the other study PRs, namely https://github.com/lichess-org/mobile/pull/1109 https://github.com/lichess-org/mobile/pull/1077 and https://github.com/lichess-org/mobile/pull/990. If you want to try out the whole feature, it's probably easiest to create a local branch based on this PR and then rebase it onto the other ones.
[study_screen.webm](https://github.com/user-attachments/assets/7722124a-f554-4619-aa3e-7f91fd7d4463)

feat: add study screen

---

lib/src/widgets/board_table.dart

Partially fixes #585, the bottom bar is still at the very bottom, but we at least use the space on the right hand side more efficiently now.
Before:
After:
This also affects all other screens that use `BoardTable`, but I think it looks nice, for example puzzle streak:
Before:
After:

Increase move list height in tablet/landscape view

---

lib/src/model/study/study_controller.dart
lib/src/view/study/study_bottom_bar.dart
lib/src/view/study/study_gamebook.dart
lib/src/view/study/study_screen.dart
test/view/study/study_screen_test.dart

[interactiveStudy.webm](https://github.com/user-attachments/assets/ffde89b2-f38a-473d-98dd-3152e538c02d)

feat: interactive studies

---

lib/src/view/broadcast/broadcast_game_screen.dart

This pull request add border radius to the whole player widget and not on every card widget. I think it looks better this way.
Before
After
Note: I increase the radius for the screenshots to see the difference

Tweak broadcast game screen ui

---

lib/src/view/puzzle/puzzle_session_widget.dart

Hi,
not familiar with flutter but I think this small change can close this bug #1090 
please test and if you have suggestion please let me know
before
after

fix inconsistent font size in puzzle's ratingDiff

---

lib/src/view/broadcast/broadcast_boards_tab.dart
lib/src/view/broadcast/broadcast_list_screen.dart
lib/src/view/broadcast/broadcast_overview_tab.dart
lib/src/view/broadcast/broadcast_round_screen.dart
lib/src/view/play/create_custom_game_screen.dart
lib/src/view/watch/watch_tab_screen.dart
lib/src/widgets/shimmer.dart

- Correctly use sliding segmented view in a scroll view
- broadcasts now display the overview tab by default if round games are not loaded yet

Cupertino scroll view improvements

---

lib/src/model/game/game_share_service.dart
lib/src/model/settings/board_preferences.dart
lib/src/model/study/study_repository.dart
lib/src/view/study/study_screen.dart

Fixes two bugs related to the GIF creation process:
- Creating a GIF from studies while the current board theme was set to "system" did not work. It now defaults to brown.
- Sometimes depending on the current theme, the board theme preferences were not respected due to a different naming in the GIF-API . This issue affected GIF creation for games (it defaulted to brown instead of the user prefs) and studies (GIFs were not created at all).
Also, I changed the labels of the board themes to include spaces, e.g., Blue2 → Blue 2.

fix: creation of gif api

---

lib/src/model/broadcast/broadcast.dart
lib/src/model/broadcast/broadcast_providers.dart
lib/src/model/broadcast/broadcast_repository.dart
lib/src/model/common/id.dart
lib/src/model/settings/general_preferences.dart
lib/src/view/broadcast/broadcast_boards_tab.dart
lib/src/view/broadcast/broadcast_game_screen.dart
lib/src/view/broadcast/broadcast_overview_tab.dart
lib/src/view/broadcast/broadcast_player_widget.dart
lib/src/view/broadcast/broadcast_players_tab.dart
lib/src/view/broadcast/broadcast_round_screen.dart
lib/src/view/home/home_tab_screen.dart
lib/src/view/play/quick_game_matrix.dart
lib/src/view/user/perf_stats_screen.dart
lib/src/widgets/progression_widget.dart

[broadcast_players.webm](https://github.com/user-attachments/assets/a430577e-b537-482d-8a27-aa89984accd6)
Tablet :

Broadcast players tab

---

lib/src/model/game/game_share_service.dart
lib/src/model/study/study_repository.dart
lib/src/view/broadcast/broadcast_boards_tab.dart
lib/src/view/broadcast/broadcast_game_bottom_bar.dart
lib/src/view/broadcast/broadcast_game_screen.dart
lib/src/view/broadcast/broadcast_round_screen.dart
lib/src/view/study/study_screen.dart

Adds share URL, download PGN and GIF Options to the broadcast game screen
**Preview**:
[broadcasts-share.webm](https://github.com/user-attachments/assets/51b197dc-2753-43b5-a94c-b488aaa21237)
**Remarks**:
- I refactored the GIF functionality from study into `game_share_service` and reused it for broadcasts.
- The broadcast name and round name are not necessary for the URL, but I believe including them is better, as it helps to humanly read the URL.
- I decided against adding the screenshot position option. I can implement it if you think its needed, but I think this feature is unnecessary on mobile devices.

feature: share option in the broadcast game screen

---

.gitignore
lib/src/view/account/edit_profile_screen.dart

Changes made to the edit profile page include:
* Removed padding from top and bottom outside ListView and added padding inside ListView.
* Added scroll behavior and GestureDetector to hide keyboard.
* Refactored to use widgets instead of functions for performance.
* Each field owns it controller ensuing dispose is called.
* closes #1245
* Made screen pop on successful save.
* trimmed all text fields before upload.
* added PopScope to reduce accidental data loss.
Some kind of dialog should be displayed before exiting, but that will require changing the appbar and I haven't quite figured out all the custom widgets to maintain native feel.

Edit profile page changes, closes The biography resets when reducing the keyboard #1245

---

lib/src/view/analysis/analysis_screen.dart

Remove flip board from the analysis menu because it is already present in the bottom bar

Tweak analysis screen

---

lib/src/model/analysis/analysis_controller.dart
lib/src/model/analysis/analysis_preferences.dart
lib/src/model/broadcast/broadcast_game_controller.dart
lib/src/model/engine/evaluation_service.dart
lib/src/model/puzzle/puzzle_controller.dart
lib/src/model/study/study_controller.dart

Fix engine evaluation started from new analysis screens

---

lib/src/model/puzzle/puzzle_controller.dart
lib/src/view/puzzle/puzzle_screen.dart
lib/src/view/puzzle/puzzle_session_widget.dart
lib/src/view/puzzle/streak_screen.dart

https://github.com/lichess-org/mobile/issues/1263 
Fix: Puzzle streak reset when app is terminated #1263
Change:
- Instead of saving the result only when the user leaves the screen, it is now saved after a puzzle is loaded.
Result:
https://github.com/user-attachments/assets/a40337f8-1976-44ef-b8da-b49468d50949

fix: 1263 puzzle streak reset when app is terminated

---

lib/src/widgets/pgn.dart
test/view/analysis/analysis_screen_test.dart

This bug only occurs if a mainline part consists of a single move - In that case, tapping a move in one of its sidelines will not invalidate the subtree cache, leading to the "current move" highlight not being updated.
Demonstration of the bug:
[bug.webm](https://github.com/user-attachments/assets/5969786d-c8d9-47c4-9b5f-975dd8f38d1c)
With this PR:
[fix.webm](https://github.com/user-attachments/assets/2a019d0c-9b18-445c-adea-b81c0f81a6c2)

fix: off-by-one error in tree view caching logic

---

lib/src/view/watch/watch_tab_screen.dart

Don't show section title for broadcast when there is no items to make it consistent with the two others sections.

Tweak watch tab

---

lib/src/view/broadcast/broadcast_boards_tab.dart
lib/src/view/broadcast/broadcast_round_screen.dart
lib/src/widgets/shimmer.dart

Revert changes of `shimmer.dart` and remove the shimmers widget in broadcast that are not currently used and causes `pumpAndSettle` in tests to time out

Revert shimmer changes

---

lib/src/view/game/game_body.dart
lib/src/view/game/game_player.dart

Fixes bug #1329 
Confirm move dialog does not disappeared when back arrow is pressed to visualize previous positions (it disappears correctly in web app). It's a problem not only related to correspondence chess, but to all time controls where "Move confirmation" preference is set.
To fix it, an additional condition is added (in GamePlayer widget) to show the ConfirmMove widget: 'canGoForward ==false' (the same condition used to disable the forward button). To achieve this, an additional parameter 'canGoForward' is added to the GamePlayer widget constructor..

Fix: Correspondence confirm move behavior #1329 v2

---

docs/setting_dev_env.md
lib/src/network/http.dart
lib/src/network/socket.dart

- completed the android emulator troubleshooting section
- added the section on setting up a real device
- moved the When using a manually installed lila server and When using lila-docker sections that were in Setting up the emulators to the Run section
- changed the content of When using lila-docker
- moved some part of Local lila server (manual installation) to Run and also small changes to Run
I also changed the scheme when using a private ip address for the host so that you can connect to a local lila from your android phone without using `adb reverse`.

Improve documentation on setting a dev environment

---

lib/src/view/play/challenge_odd_bots_screen.dart
lib/src/view/play/online_bots_screen.dart
lib/src/view/user/user_screen.dart

closes #796 . Implements challenges featured leela bots with piece odds. The bots can now only be challenged with time controls and positions they will accept: 
video of phone: 
https://github.com/user-attachments/assets/e3398388-cf75-432d-bbf4-f59ebed3c307
video of tablet :
https://github.com/user-attachments/assets/0b33d103-9bf9-41e1-9a53-d8f059d77c28
Remarks:
- I'm unsure if the current method for storing the positions of the different bots is the nicest. Suggestions are welcome.
- The new bot, [LeelaPieceOdds](https://lichess.org/@/LeelaPieceOdds), supports a wide range of starting positions (as shown in the phone video). This might be overwhelming; feedback on better ways to handle this would be appreciated.
- I couldn't test it with the real bots since challenging them on …

challenge leela odd bots

---

lib/src/view/coordinate_training/coordinate_training_screen.dart
pubspec.lock
pubspec.yaml
test/view/coordinate_training/coordinate_training_screen_test.dart

Fixes #1017
Needs https://github.com/lichess-org/flutter-chessground/pull/66

fix: use Chessboard instead of ChessboardEditor for coordinate training

---

.github/workflows/test.yml

Fix CI tests by installing SQlite dependencies on Ubuntu that are required for Dart package sqflite_common_ffi

Fix CI tests 

---

lib/src/view/user/user_profile.dart

Issue
------
[Issue #1372](https://github.com/lichess-org/mobile/issues/1372)
Description
-----------
This pull request introduces a feature that displays country or location information under the flag. It also provides multiple display modes: full (country + location), only country, only location, or none, and these details are always visible.
Comparison
----------
Below is a table comparing the old, new, and web versions:
|                 | Before                 | After                 | Web                 |
|-----------------|---------------------|---------------------|---------------------|
| Full            | ![old_full](https://github.com/user-attachments/assets/f49a6c72-960a-450b-98f8-d81381d37d38) | ![new_full](https://github.com/user-attachments/assets/b24c8602-9472-4eab-805c-8 …

Improve user profile location display logic

---

lib/src/view/game/game_body.dart
lib/src/widgets/bottom_bar_button.dart

Issue: https://github.com/lichess-org/mobile/issues/755
This PR adds a blink effect to the next button when the user is not at the latest move during game reviews.
| before | after | lichess.org |
|---------|---------|---------|
| ![Screenshot_1737730675](https://github.com/user-attachments/assets/a42896a5-09e8-4078-a741-c4234e509694) | ![untitled](https://github.com/user-attachments/assets/f87130e8-66a7-4f4e-8241-aca58ee51a55) | ![Screen-Recording-2025-01-24-at-18 22 39](https://github.com/user-attachments/assets/a116a21b-eff0-4729-be5c-16c3fb1d0292) |

Add blink effect to next button based on game step cursor

---

lib/src/model/clock/clock_tool_controller.dart

For #1307.
The `lowTime` sound will be played when the clock reaches 10% of the total duration.

Added emergency sound to the clock tool

---

lib/src/model/analysis/analysis_controller.dart
lib/src/model/common/eval.dart
lib/src/model/common/node.dart
lib/src/model/engine/evaluation_service.dart
lib/src/model/engine/uci_protocol.dart
lib/src/model/engine/work.dart
lib/src/model/study/study_controller.dart
lib/src/view/analysis/analysis_screen.dart
lib/src/view/broadcast/broadcast_game_screen.dart
lib/src/view/engine/engine_depth.dart
lib/src/view/engine/engine_lines.dart
lib/src/view/study/study_screen.dart
test/model/common/node_test.dart

- Rename the current `ClientEval` class to `LocalEval` so that we can add a new sealed class `ClientEval` that will have common properties between `CloudEval` and `LocalEval`. The website client also does something similar https://github.com/lichess-org/lila/blob/c51ca345338892a742d676bcda87de9a1e1e6c5e/ui/%40types/lichess/tree.d.ts#L20.
- Add the sealed class `ClientEval` and the class `CloudEval`
- Tweak doc comments on the eval classes

Prepare cloud eval

---

lib/src/view/user/perf_stats_screen.dart

Fix elo chart by not showing it if there is only one point.
The website still chooses to show the graph even if there is only one point but I think it is fine to not do it.

Fix elo chart 

---

lib/src/view/broadcast/broadcast_boards_tab.dart
lib/src/view/broadcast/broadcast_round_screen.dart

[broadcast_playing_toggle_3.webm](https://github.com/user-attachments/assets/4910a717-88a6-4734-9c9b-2bb0d7213911)

Add a filter to show only playing games in a broadcast round

---

lib/src/model/study/study.dart
lib/src/model/study/study_controller.dart
lib/src/view/study/study_bottom_bar.dart
test/view/study/study_screen_test.dart

feat: show chapter numbers

---

lib/src/view/broadcast/broadcast_boards_tab.dart

When switching to different round, the evals may not be updated until the view is scrolled. This problem was due to the key not being unique.

Fix broadcast eval bar not working when switching to a different round

---

lib/src/view/broadcast/broadcast_overview_tab.dart

Opening a url might fail in the description of a broadcast overview if it is a relative url (e.g. /fide/1503014/-). This PR fixes it by using `Uri.resolve`

Support relative uri reference in broadcast markdown description

---

android/app/src/main/AndroidManifest.xml
lib/src/app_links.dart
lib/src/view/broadcast/broadcast_game_screen.dart
lib/src/view/broadcast/broadcast_player_results_screen.dart
lib/src/view/broadcast/broadcast_player_screen_providers.dart

Add deeplink support for broadcast games.

Broadcast game deeplink

---

lib/src/model/analysis/analysis_controller.dart
lib/src/model/broadcast/broadcast_analysis_controller.dart
lib/src/model/common/node.dart
lib/src/model/engine/evaluation_service.dart
lib/src/model/study/study_controller.dart
lib/src/view/analysis/tree_view.dart
lib/src/view/study/study_tree_view.dart
lib/src/widgets/pgn.dart

Show eval in move list when 2 columns

---

lib/src/model/analysis/analysis_controller.dart
lib/src/model/broadcast/broadcast_analysis_controller.dart
lib/src/model/common/eval.dart
lib/src/model/engine/evaluation_service.dart
lib/src/view/analysis/analysis_screen.dart
lib/src/view/broadcast/broadcast_game_screen.dart
lib/src/view/engine/engine_depth.dart
lib/src/view/engine/engine_gauge.dart
lib/src/view/engine/engine_lines.dart
lib/src/view/study/study_screen.dart

Prepare cloud eval implementation :
- add websocket eval events in BroadcastAnalysisController
- use ClientEval type instead of LocalEval in AnalysisCurrentNode and engine widgets
- add doc comments and necessary properties to ClientEval
- edit engine depth widget to display a cloud icon when it is a cloud eval (see screenshot below)

Cloud eval preparation

---

lib/src/model/tv/tv_controller.dart

This way we can reuse it, e.g. for watching the featured game of a tournament.
In the future, this could also be useful to implement the "watch a player" feature.

feat: allow using TvController w/o providing a channel

---

lib/src/view/broadcast/broadcast_list_screen.dart
pubspec.lock
pubspec.yaml
test/view/broadcast/broadcast_list_screen_test.dart
test/view/broadcast/broadcast_round_screen_test.dart

The test for iOS is failing because the finder in `scrollUntilVisible` needs to match a single element and for iOS there are two text widgets that appears with _Completed_ so I don't know how to fix this test. Maybe we can just remove it or make a separate test for Android and iOS ?

Fix iOS broadcast test

---

lib/src/model/analysis/analysis_controller.dart
lib/src/model/broadcast/broadcast_analysis_controller.dart
lib/src/model/engine/evaluation_mixin.dart
lib/src/model/puzzle/puzzle_controller.dart
lib/src/model/study/study_controller.dart
lib/src/view/broadcast/broadcast_game_screen.dart
lib/src/view/engine/engine_depth.dart
lib/src/widgets/buttons.dart
test/view/analysis/analysis_screen_test.dart
test/view/engine/engine_depth_test.dart
test/view/engine/engine_gauge_test.dart
test/view/engine/engine_lines_test.dart
test/view/engine/test_engine_app.dart

Also fix the always disabled broadcast engine toggle button.

Only delay local engine evaluation if cloud eval is likely available

---

lib/src/view/broadcast/broadcast_game_screen.dart

Fix a bug I introduced in this PR https://github.com/lichess-org/mobile/pull/1509.
I accidentally removed the `on` in `onSecondaryContainer`.

Fix broadcast bug

---

lib/src/model/broadcast/broadcast_analysis_controller.dart

Close #1443.
Fix broadcast game reload last move not updated correctly when not on broadcast path and fix current node not updated when on broadcast path.

Fix broadcast game reload

---

ios/Podfile.lock
lib/src/model/common/service/sound_service.dart
lib/src/model/settings/general_preferences.dart
pubspec.lock
pubspec.yaml

- Can now play max 2 sounds simultaneously
- Execute iOS channel handlers in a background thread
Closes #1152

Improve sound effects

---

lib/src/model/analysis/analysis_controller.dart
lib/src/model/analysis/opening_service.dart
test/model/analysis/fake_opening_service.dart

closes https://github.com/lichess-org/mobile/issues/1495
Refactored opening fetching logic to use FEN instead of move sequences. This change ensures precise identification of chess openings on the analysis board and opening explorer, addressing issue 1495.

Refactor opening fetching to use FEN instead of moves

---

lib/src/view/game/game_player.dart

Problem: If no move has been made yet, `materialDiff` is `null` and its widget won't be displayed. This leads to a layout jump when the first move is made.
Solution: Make the `materialDiff` field inside `MaterialDifferenceDisplay` nullable
Before: 
[before.webm](https://github.com/user-attachments/assets/0cc7c365-a734-40e0-b06f-8af945ced6d2)
After:
[after.webm](https://github.com/user-attachments/assets/5bfe320a-2f41-4b1b-b168-24029522fdcf)

fix: prevent move list from resizing when first move is made

---

pubspec.lock
pubspec.yaml

I was wondering if we want to pin the Dart version since we are doing it for the Flutter version or if we prefer to use `^`.

Update Flutter version

---

lib/src/model/game/over_the_board_game.dart
lib/src/model/over_the_board/over_the_board_game_controller.dart
lib/src/view/over_the_board/over_the_board_screen.dart

This pr adds three new features to over the board games: resign, offer draw, and a notification on threefold repetition. No new widget or class was added, and these features were implemented much like they are in regular online games.
Fixes #1029 
**Changes made:**
- OverTheBoardGame model class: Added three new getters: abortable, resignable and drawable. Calculated the same way as in the Game model class.
- OverTheBoardGameController: Added two new functions: resign() and draw(). Also added a check for a threefold repetition on every move.
- OverTheBoardScreen: Added a hamburger menu to the UI, added listeners for the new controller functions, and used YesNoDialog to request user confirmations.
**Tests performed:**
- Ran flutter test. Some tests failed, but these were not due to any …

Over the board feats: Resign, Offer Draw and notification on threefold repetition

---

lib/src/model/user/profile.dart

Add 'GitLab' to the LinkSite instance in UserProfile for any URL matching 'https://gitlab.com/*'.
<table>
<tr>
<th>Before</th>
<th>After</th>
</tr>
<tr>
<td><img src="https://github.com/user-attachments/assets/88d51b00-244a-4128-805e-9c11ba9fc8c6" alt="Before" width="300"/></td>
<td><img src="https://github.com/user-attachments/assets/d35bb47a-f081-434f-ace8-d019ed1b2f42" alt="After" width="300"/></td>
</tr>
</table>

feat: Add GitLab to LinkSite

---

lib/src/model/tv/tv_controller.dart

Revert [allow using TvController w/o providing a channel](https://github.com/lichess-org/mobile/commit/cf31c4cb96d732bfa16f50db8d9aa6de0d0d53c5) because it is actually not possible to use the TV controller for the tournament featured game.

Revert allow using TvController w/o providing a channel

---

lib/src/view/home/home_tab_screen.dart

#1619 Adds a dynamic icon to home screen greeting that changes based on the time of day:
- Displays ☀️ between 6:00 AM and 5:59 PM (generic daytime)
- Displays 🌙 between 6:00 PM and 5:59 AM (generic nighttime)
In a more advanced implementation, if the user's country is available in their profile, we could use the average latitude and longitude in combination with the current date to estimate these times more accurately. However, this might be an over-engineered solution for the current use case.

Add time-based greeting icon (☀️/🌙) #1619

---

lib/src/model/analysis/analysis_controller.dart
lib/src/model/broadcast/broadcast_analysis_controller.dart
lib/src/model/common/chess.dart
lib/src/model/engine/evaluation_mixin.dart
lib/src/model/engine/evaluation_preferences.dart
lib/src/model/puzzle/puzzle_controller.dart
lib/src/model/study/study_controller.dart
lib/src/view/analysis/analysis_settings_screen.dart
lib/src/view/analysis/engine_settings_widget.dart
lib/src/view/broadcast/broadcast_game_settings_screen.dart
lib/src/view/settings/engine_settings_screen.dart
lib/src/view/study/study_settings.dart
test/view/analysis/analysis_screen_test.dart
test/view/engine/engine_depth_test.dart

Partially adresses #1623
Changes:
- cloud evals are not requested if ply > 15 (unless for broadcasts)
- cloud eval don't override anymore deeper local eval
- deeper local eval will not override cloud eval
- local eval will always override cloud eval if search time settings is set to 'infinity'
- cloud eval will not be requested if a threefold repetition pattern is detected
-

Better filter cloud evals

---

lib/src/model/study/study_controller.dart

Making `evaluationContext` nullable might be an alternative solution
Fixes #1662

fix: studies with illegal positions

---

lib/main.dart

When I run the app on a physical tablet device, the display size is reported as 0. This leads the app to incorrectly enforce portrait orientation. This is the relevant code snippet:
https://github.com/lichess-org/mobile/blob/83e6f4ad602a6418c2bfb18b5ac631f0db342dbf/lib/src/init.dart#L144-L149
According to the documentation in https://api.flutter.dev/flutter/dart-ui/FlutterView/physicalSize.html:
> At startup, the size of the view may not be known before Dart code runs. If this value is observed early in the application lifecycle, it may report [Size.zero](https://api.flutter.dev/flutter/dart-ui/Size/zero-constant.html).
Delaying the call to the androidDisplayInitialization function solves the problem.

fix orientation incorrectly locked to portrait on tablet

---

lib/src/view/analysis/analysis_screen.dart

Currently the only options for sharing a game URL, from what I can tell are:
1. Share the PGN with the platform share activity, which includes the URL.
2. Manually copy the game URL
I often will want to share a game directly to a friend on Whatsapp for him to view on the website/app so an entire PGN is unnecessary.
This PR adds a new button to share the URL via the share activity directly from the main analysis board menu.

Add button to share only game URL

---

android/app/build.gradle

Add the native debug symbols in the Android App Bundle of the app with debug symbol level full.
See the following Android documentation about native symbols https://developer.android.com/build/include-native-symbols for more information.

Add the native debug symbols in the AAB

---

android/app/build.gradle

I don't know if there was a reason to enable only minify and not shrink resources but the [Android documentation](https://developer.android.com/topic/performance/app-optimization/enable-app-optimization) recommends to enable both.

Enable shrink resources on android release builds

---

lib/src/theme.dart

Reverts lichess-org/mobile#1685
Got feedback that transitions were really slow some times.
As is it still not included by default on flutter side, perhaps some improvements are still to be made.

Revert "use FadeForwardsPageTransitionBuilder"

---

lib/src/app_links.dart
lib/src/model/analysis/analysis_controller.dart
lib/src/model/game/game_controller.dart
lib/src/view/account/game_bookmarks_screen.dart
lib/src/view/analysis/analysis_screen.dart
lib/src/view/board_editor/board_editor_screen.dart
lib/src/view/correspondence/offline_correspondence_game_screen.dart
lib/src/view/game/game_common_widgets.dart
lib/src/view/game/game_list_tile.dart
lib/src/view/game/game_result_dialog.dart
lib/src/view/more/load_position_screen.dart
lib/src/view/more/more_tab_screen.dart
lib/src/view/opening_explorer/opening_explorer_widgets.dart
lib/src/view/over_the_board/over_the_board_screen.dart
lib/src/view/puzzle/puzzle_screen.dart
lib/src/view/puzzle/streak_screen.dart
lib/src/view/study/study_bottom_bar.dart
lib/src/view/user/game_history_screen.dart
lib/src/view/user/perf_stats_screen.dart
test/view/analysis/analysis_screen_test.dart
test/view/engine/test_engine_app.dart
test/view/opening_explorer/opening_explorer_screen_test.dart

The `gameId` and `standalone` properties have always been exclusive (exactly one of them had to be non-null), so I think this better expresses the intent.
Additionally, for analysing ongoing correspondence games, I'd introduce a new constructor in https://github.com/lichess-org/mobile/pull/1802 along the lines of
```
AnalysisOptions.ongoingCorrespondenceGame({
required Side orientation,
int? initialMoveCursor,
required GameFullId gameId,
}) = OngoingCorrespondenceGame;
```

refactor: make AnalysisOptions a union type

---

lib/src/model/analysis/analysis_controller.dart
lib/src/model/broadcast/broadcast_analysis_controller.dart
lib/src/view/analysis/analysis_settings_screen.dart
lib/src/view/analysis/server_analysis.dart
lib/src/view/broadcast/broadcast_game_screen.dart
lib/src/view/broadcast/broadcast_game_settings_screen.dart
lib/src/widgets/pgn.dart
test/view/analysis/analysis_screen_test.dart
test/view/broadcast/broadcast_game_screen_test.dart

This PR changes the behaviour of the "Computer analysis" switch in analysis (and broadcast) settings.
The reason: some people don't want to be spoiled by the automatic server analysis (which can be requested by anyone). So we want a switch to disable it completely, but still allowing the local engine on demand.
Before:
- computer analysis OFF would disable both server analysis (variations, evals, annotations) AND local analysis
Now:
- computer analysis OFF will only disable server analysis; that is, the local engine is still available
This PR also fixes a bug where in the default two columns move list notation, the server analysis variations where displayed even if the switch was off.

Allow to disable server analysis and use the local engine at the same time

---

lib/src/view/puzzle/streak_screen.dart

Closes #1951
This issue occurred because the `PuzzleController` was stuck in the `PuzzleMode.view` mode after an incorrect move. The  `PuzzleController` never transitions into `PuzzleMode.play`, which allows the puzzle to be played. This is because the `PuzzleController` and the `PuzzleStreakController` aren't properly synchronised. Under some scenarios, like when the very first move of a puzzle streak is incorrect, the `PuzzleController` retains the old state, and the puzzle does not advance properly.
This pull request adds a listener to detect when the state of the `PuzzleStreakController` changes, and updates it in `PuzzleController`, allowing the new puzzle to be played.

fix: manually update the puzzle context when the puzzle changes

---

lib/src/view/game/game_loading_board.dart
lib/src/view/user/game_history_screen.dart

closes #2077 #2076 #2035
- Localizes the numbers on the game seek screen aswell as on the game history screen
- Makes the Rating Range RatingPrefAware
- If the default value for the rating range is used, the rating range it is not displayed

Fix game seek rating and localize numbers

---

lib/src/model/study/study_controller.dart

Fixes a bug reported on discord. Problem appeared due to the variant of an illegal position being set to `fromPosition` and therefore having no initial position. 
Bugfix tested on this study: https://lichess.org/study/UUSBv8yN

Fix another study loading issue

---

lib/src/view/tournament/tournament_screen.dart

Colors the results not according to points, but according to results, similar to what is done on the website now:

indicate game results in tournament player view with colors

---

lib/src/view/study/study_gamebook.dart

The scroll position in the study comment persists even after the text is changed. 
This results in behaviour that results in the user having to manually scroll to the top of the comment if they want to read the text.
This PR resets the scroll position when the widget changes, to save the user having to manually scroll.

fix: reset scroll when navigating study chapters

---

lib/src/view/account/profile_screen.dart
lib/src/view/broadcast/broadcast_list_screen.dart
lib/src/view/home/home_tab_screen.dart
lib/src/view/message/contacts_screen.dart
lib/src/view/play/correspondence_challenges_screen.dart
lib/src/view/settings/http_log_screen.dart
lib/src/view/tournament/tournament_list_screen.dart
lib/src/view/watch/watch_tab_screen.dart
lib/src/widgets/haptic_refresh_indicator.dart

Add haptic feedback when refreshing pages. 
This is done by creating a wrapper, `HapticRefreshIndicator`, around the normal `RefreshIndicator`. This wrapper then triggers haptic feedback when the refresh takes place.
This wrapper can be used as an (almost) drop-in replacement for `RefreshIndicator`.
Closes #2025

feat: add haptic feedback for page refreshes

---

lib/src/view/clock/clock_tool_screen.dart

https://github.com/user-attachments/assets/0403d2c6-05a9-4e97-a31a-014104f817ed
here you can see both behaviour
iPad A16 is what we have now
iPad 8th generation is what we will get after updating

Fixing Clock Misorientation in tablets

---

lib/src/model/board_editor/board_editor_controller.dart
pubspec.lock
pubspec.yaml
test/view/board_editor/board_editor_screen_test.dart

Small UX improvement for the editor: 
Empties the square after tapping it again with the same piece in hand. This is possible on the website too.
Tests failing is expected, needs chessground changes.

Discard piece after tapping square again in Editor
