android/gradle.properties, lib/src/ui/user/user_screen.dart, pubspec.lock
when a player has not yet made a single game or obtained an appropriate kClueLessDeviation a empty space is show. That is horrible to the UI and considered a bad practise. The following changes were made...
Before             |  After
:-------------------------:|:-------------------------:
when tapping on the play button the player will be forward to the play screen
=> Fix empty space issue in rating section of profile screen.

lib/src/model/puzzle/puzzle_providers.dart, lib/src/ui/puzzle/puzzle_screen.dart, lib/src/ui/puzzle/puzzle_session_widget.dart, lib/src/ui/puzzle/puzzle_streak_screen.dart, lib/src/ui/puzzle/puzzle_view_model.dart
=> Load puzzle from session

lib/src/ui/user/user_screen.dart
=> Fix Stockfish null 

lib/src/model/account/account_repository.dart, lib/src/model/game/game_repository_providers.dart, lib/src/model/user/user_repository.dart, lib/src/model/user/user_repository_providers.dart, lib/src/ui/account/profile_screen.dart, lib/src/ui/puzzle/puzzle_dashboard_screen.dart, lib/src/ui/puzzle/puzzle_dashboard_widget.dart, lib/src/ui/user/leaderboard_widget.dart, lib/src/ui/user/user_activity.dart, lib/src/ui/user/user_screen.dart, lib/src/ui/watch/watch_screen.dart, lib/src/widgets/buttons.dart, lib/src/widgets/feedback.dart, lib/src/widgets/list.dart, lib/src/widgets/shimmer.dart
- add shimmer effect to list section loading
- only cache requests on success
- allow users to retry failed profile request
- fix decoding of user activity when empty
Resolves #91
=> Improve loading states

lib/src/app.dart, lib/src/widgets/bottom_navigation.dart, pubspec.lock, pubspec.yaml
=> Enabled high refresh rate for devices where it was previously disabled

lib/src/ui/user/user_screen.dart
=> Fix recent game trailing result

lib/src/utils/json.dart
Resolves #153 
I tested it and it matches the website on my profile.
=> Fix timeline date error 

lib/src/ui/game/archived_game_screen.dart, lib/src/widgets/buttons.dart
close #143
I had to remove the tooltip for the bottom button as it won't work with it.
=> Rewind moves

lib/src/model/puzzle/puzzle_providers.dart, lib/src/model/puzzle/puzzle_repository.dart, lib/src/model/puzzle/storm.dart, lib/src/ui/puzzle/storm_dashboard.dart, lib/src/ui/puzzle/storm_screen.dart, lib/src/ui/user/user_screen.dart
=> Storm dashboard

lib/src/model/puzzle/storm.dart, lib/src/model/puzzle/storm_ctrl.dart, lib/src/ui/puzzle/storm_screen.dart, lib/src/widgets/buttons.dart
=> Storm Filter

android/app/src/main/AndroidManifest.xml
=> Disable split screen 

lib/src/view/puzzle/puzzle_screen.dart, test/ui/puzzle/puzzle_screen_test.dart
=> Add delay to puzzle solution button

lib/main.dart
=> Translate timeago

lib/src/view/puzzle/storm_clock.dart, lib/src/view/puzzle/storm_screen.dart
=> Fix storm clock issue

lib/src/model/game/game_ctrl.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/game/game_screen.dart, lib/src/view/puzzle/puzzle_screen.dart, lib/src/view/puzzle/storm_screen.dart, lib/src/view/puzzle/streak_screen.dart, lib/src/widgets/board_table.dart, pubspec.lock, pubspec.yaml
=> Cancel premove when connection reset and after takeback

.fvm/fvm_config.json, .gitignore, README.md
=> integrate: fvm (flutter version management)

lib/src/model/analysis/analysis_controller.dart, lib/src/view/analysis/tree_view.dart, lib/src/widgets/buttons.dart
=> Add analysis context menu

lib/src/view/puzzle/storm_screen.dart
fixes #445 by reseting the clock
=> Reset Clock on new run, fixes #445

lib/src/model/lobby/create_game_service.dart, lib/src/model/lobby/game_seek.dart, lib/src/model/lobby/game_setup.dart, lib/src/model/lobby/lobby_repository.dart, lib/src/view/game/standalone_game_screen.dart, lib/src/view/home/home_tab_screen.dart, lib/src/view/play/common_play_widgets.dart, lib/src/view/play/create_correspondence_game_screen.dart, lib/src/view/play/create_custom_game_screen.dart, lib/src/view/play/play_screen.dart, lib/src/view/play/time_control_modal.dart
=> Add support for rating range when looking for a new opponent

lib/src/view/analysis/analysis_screen.dart
=> Fix analysis summary name height

lib/src/view/game/game_result_dialog.dart, lib/src/widgets/adaptive_action_sheet.dart
closes #435
Improved the action list as well. Haven't tested for the game end dialog because I can't start a game but it should work. 
<details><summary>Preview</summary>
<p>
</p>
</details>
=> Improve tablet game info popup

lib/src/model/puzzle/puzzle_providers.dart, lib/src/model/puzzle/puzzle_repository.dart, lib/src/view/puzzle/puzzle_dashboard_widget.dart, lib/src/view/puzzle/puzzle_tab_screen.dart, test/model/puzzle/puzzle_repository_test.dart
it's more confusing than it is useful.
Closes #498
=> remove puzzle dashboard days selector - closes #498

lib/src/model/user/profile.dart, lib/src/view/account/edit_profile_screen.dart
closes #502 
The new line fix is not tested.
=> Fix social links

lib/src/view/game/game_result_dialog.dart
=> Disable touch on acpl chart preview graph

lib/src/view/analysis/analysis_screen.dart, lib/src/view/game/game_result_dialog.dart, lib/src/view/game/message_screen.dart
Improves the error messages when an anon user requests an analysis or wants to chat.
=> improve anon error messages

lib/src/model/common/perf.dart, lib/src/model/user/user.dart, lib/src/view/user/perf_cards.dart
=> Added storm and streak high scores on user profile

lib/src/navigation.dart
=> Improve bottom bar icons

lib/src/view/user/perf_stats_screen.dart
=> Remove worst rated defeats in perf stats screens

lib/src/app.dart, lib/src/db/database.dart, lib/src/log.dart, lib/src/model/analysis/analysis_controller.dart, lib/src/model/analysis/server_analysis_service.dart, lib/src/model/common/http.dart, lib/src/model/common/socket.dart, lib/src/model/game/chat_controller.dart, lib/src/model/game/game_controller.dart, lib/src/model/game/playable_game.dart, lib/src/model/lobby/create_game_service.dart, lib/src/model/lobby/lobby_numbers.dart, lib/src/model/lobby/lobby_repository.dart, lib/src/model/relation/relation_ctrl.dart, lib/src/model/tv/live_tv_channels.dart, lib/src/model/tv/tv_controller.dart, lib/src/view/account/edit_profile_screen.dart, lib/src/view/game/game_body.dart, lib/src/view/game/game_loading_board.dart, lib/src/view/game/game_settings.dart, lib/src/view/game/lobby_screen.dart, lib/src/view/game/message_screen.dart, lib/src/view/play/create_correspondence_game_screen.dart, lib/src/view/puzzle/puzzle_screen.dart, lib/src/view/puzzle/puzzle_tab_screen.dart, lib/src/view/relation/relation_screen.dart, test/model/common/socket_test.dart
Closes #404 
Changes:
- introduces a `SocketPool` which maintains a active socket connection on default route ; this allows to inform other players that the user is online
- previous behaviour is kept: the pool will close automatically idle sockets
=> Socket refactoring

lib/src/model/analysis/analysis_controller.dart, lib/src/model/analysis/server_analysis_service.dart, lib/src/model/common/id.dart, lib/src/model/game/game_socket_events.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/game/game_result_dialog.dart
=> Fix request analysis issues

lib/src/view/game/game_body.dart
=> Remove .remainder(60) from opponentLeftCounter

lib/src/view/analysis/analysis_screen.dart
adds the result to the analysis screen 
<details>
<summary>preview</summary>
</details>
=> add result to gameanalysis

lib/src/view/user/perf_stats_screen.dart
=> Stats Screen Variant Selector

lib/src/model/game/game_controller.dart
=> Disable premove while navigating history

lib/src/view/analysis/analysis_screen.dart, lib/src/view/puzzle/puzzle_screen.dart, lib/src/widgets/board_table.dart
=> Fix misplaced pieces

lib/src/view/puzzle/streak_screen.dart
=> Fix puzzle streak

lib/src/view/game/game_body.dart
=> resolves #654

lib/src/view/analysis/analysis_screen.dart
- The position of vertical bar was offset by one move
- Opening vertical bar should only be shown if API returned division information
=> Fix game phases

lib/src/view/game/game_body.dart
=> fix flip board functionality

lib/src/view/analysis/analysis_screen.dart
=> Allow the user to drag the line on acpl chart

lib/src/view/analysis/analysis_screen.dart
=> Fix game phases overlapping

lib/src/model/lobby/create_game_service.dart, lib/src/view/game/game_loading_board.dart, lib/src/view/game/lobby_screen.dart
=> Fix getting new opponent from lobby screen

lib/src/view/settings/account_preferences_screen.dart
=> Fix profile preferences screen when offline

lib/main.dart, lib/src/model/puzzle/storm_controller.dart, lib/src/model/settings/board_preferences.dart, lib/src/utils/gestures_exclusion.dart, lib/src/utils/immersive_mode.dart, lib/src/view/clock/clock_settings.dart, lib/src/view/clock/clock_tile.dart, lib/src/view/game/game_body.dart, lib/src/view/puzzle/puzzle_history_screen.dart, lib/src/view/puzzle/puzzle_tab_screen.dart, lib/src/view/puzzle/storm_clock.dart, lib/src/view/puzzle/storm_screen.dart, lib/src/view/settings/account_preferences_screen.dart, lib/src/view/settings/board_behavior_settings_screen.dart, lib/src/view/settings/settings_screen.dart
- Use edge to edge mode on compatible devices
- Immersive mode during play is now opt it, because it is not obvious that a majority of people would be bothered by system gestures (it depends a lot on the device and if the user swipes to move the piece or not).
- gestures exclusion are now disabled on tablets
- Improve storm screen gestures exclusion settings
=> Improve Android system bars and immersive mode

lib/src/view/game/game_list_tile.dart, lib/src/view/user/recent_games.dart
=> Fix wrong orientation in anon game list

lib/src/view/puzzle/puzzle_tab_screen.dart, lib/src/view/settings/settings_screen.dart, lib/src/view/tools/tools_tab_screen.dart, lib/src/view/watch/watch_tab_screen.dart
If back button is used in a tab which is not home, and navigator stack is empty, then return to home.
Closes #696
=> Return to home tab with android back button

lib/src/styles/styles.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/game/game_result_dialog.dart
=> Improve eval chart colors

lib/src/model/game/game_controller.dart, lib/src/model/game/playable_game.dart, lib/src/view/game/game_body.dart, lib/src/view/game/game_player.dart, lib/src/view/game/game_settings.dart
- zen mode now doesn't prevent to see material difference
- zen mode is only active when the game is playable
Closes #722
=> Fix zen mode

lib/src/model/lobby/game_setup.dart, lib/src/view/play/common_play_widgets.dart
=> allow rating range filter from +-0 instead of +-50

lib/src/view/analysis/analysis_screen.dart
=> feat: export fen

lib/src/view/game/game_body.dart
=> fix: disable piece animation in bullet time controls

lib/src/view/analysis/analysis_share_screen.dart
Also use a choice selector for Result tag.
Closes #786
=> Don't show rating in PGN tags if disabled

lib/src/model/account/account_preferences.dart, lib/src/model/account/account_repository.dart, lib/src/view/game/game_body.dart, lib/src/view/settings/account_preferences_screen.dart, lib/src/widgets/countdown_clock.dart
Closes #785
Needs https://github.com/lichess-org/lila/pull/15613
=> feat: support disabling clock emergency sound

lib/src/view/analysis/analysis_screen.dart, lib/src/widgets/board_table.dart, pubspec.lock, pubspec.yaml
See: https://github.com/lichess-org/flutter-chessground/pull/37
Closes #740
=> Update board gesture detector and enable drawing mode

lib/src/model/analysis/analysis_preferences.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/analysis/analysis_settings.dart, lib/src/view/analysis/tree_view.dart
[Screencast from 2024-07-13 19:55:59.webm](https://github.com/user-attachments/assets/de4c8712-a18b-4a08-a31a-170e6ebe05dd)
=> Add ability to toggle annotations in analysis board

lib/src/model/account/account_preferences.dart, lib/src/model/account/account_repository.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/analysis/tree_view.dart, lib/src/view/settings/account_preferences_screen.dart, lib/src/widgets/board_table.dart, test/model/account/account_repository_test.dart
Needs https://github.com/lichess-org/lila/pull/15703 (already merged) 
Solves #759
=> Respect piece notation setting in game and analysis (#759)

lib/src/view/puzzle/puzzle_feedback_widget.dart, test/view/puzzle/puzzle_screen_test.dart
Closes #874
with ratings disabled:
=> fix: respect "hide rating" pref in puzzle solution screen

lib/src/model/settings/board_preferences.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/settings/theme_screen.dart, lib/src/widgets/board_table.dart
Closes #841
[shapeColors.webm](https://github.com/user-attachments/assets/84ab5eef-5e28-442b-b97e-50657201a3a8)
=> feat: add setting to change shape colors

lib/src/constants.dart, lib/src/model/analysis/analysis_controller.dart, lib/src/model/common/chess.dart, lib/src/model/game/game_controller.dart, lib/src/model/puzzle/puzzle_controller.dart, lib/src/model/puzzle/storm_controller.dart, lib/src/view/analysis/analysis_board.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/correspondence/offline_correspondence_game_screen.dart, lib/src/view/game/archived_game_screen.dart, lib/src/view/game/game_body.dart, lib/src/view/game/game_loading_board.dart, lib/src/view/opening_explorer/opening_explorer_screen.dart, lib/src/view/puzzle/puzzle_screen.dart, lib/src/view/puzzle/storm_screen.dart, lib/src/view/puzzle/streak_screen.dart, lib/src/view/settings/theme_screen.dart, lib/src/view/watch/tv_screen.dart, lib/src/widgets/board_carousel_item.dart, lib/src/widgets/board_preview.dart, lib/src/widgets/board_table.dart, lib/src/widgets/board_thumbnail.dart, pubspec.lock, pubspec.yaml, test/test_app.dart, test/view/game/archived_game_screen_test.dart
=> Instant premoves

lib/src/model/game/game_controller.dart
Closes #964
[zenfix.webm](https://github.com/user-attachments/assets/45db8961-34f0-41cd-a5a6-7f8491571624)
=> fix: keep zen mode after game finishes

CONTRIBUTING.md, README.md, docs/coding_style.md, docs/setting_dev_env.md
- Move dev-setup related docs from README.md to setting_dev_env.md, some of this was duplicated between the two.
- Add "Before submitting a Pull Request" to CONTRIBUTING.md
- Add section about `PlatformWidget` to coding_style.md
=> docs: various clean ups and improvements

lib/src/view/analysis/analysis_screen.dart, lib/src/view/correspondence/offline_correspondence_game_screen.dart, lib/src/view/game/archived_game_screen.dart, lib/src/view/game/game_body.dart, lib/src/view/game/game_list_tile.dart, lib/src/view/game/game_result_dialog.dart, lib/src/view/puzzle/puzzle_screen.dart, lib/src/view/puzzle/streak_screen.dart, pubspec.lock, pubspec.yaml
This is a workaround fix.
Crash is investigated in https://github.com/lichess-org/mobile/issues/973.
=> Fix ios crash

android/app/src/main/AndroidManifest.xml
=> Disable impeller for now on android

lib/src/view/game/game_body.dart, lib/src/view/user/game_history_screen.dart, lib/src/widgets/bottom_bar_button.dart
https://api.flutter.dev/flutter/material/Badge/Badge.html
=> Use badge widget for icons

lib/src/view/game/archived_game_screen.dart, lib/src/view/opening_explorer/opening_explorer_screen.dart, lib/src/widgets/board_table.dart, lib/src/widgets/platform_scaffold.dart, test/view/game/archived_game_screen_test.dart
=> Fix loading games from explorer

lib/src/model/analysis/analysis_controller.dart, lib/src/model/engine/evaluation_service.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/analysis/analysis_share_screen.dart, lib/src/view/tools/tools_tab_screen.dart, test/view/opening_explorer/opening_explorer_screen_test.dart
=> Fix explorer prev and next button unexpected behaviour

lib/src/model/game/game_controller.dart, lib/src/view/home/home_tab_screen.dart
=> Fix correspondence game not updated after resuming application

lib/src/view/user/game_history_screen.dart, lib/src/widgets/filter.dart
I'll reuse this in the study list screen. I think the coordinate trainer config screen can even reuse this as well.
=> [Study] refactor: make _Filter from game filter public

lib/src/model/common/id.dart, lib/src/model/study/study.dart, lib/src/model/study/study_filter.dart, lib/src/model/study/study_repository.dart
Do we need separate test for json parsing here? Or is it enough to have a end-to-end test for the final study list screen?
=> [Study] add models for listing available studies

lib/src/view/analysis/analysis_screen.dart
PR implements: #992 
Also includes minor cleanup
Screenshots:
=> feat: [Analysis Board] Added option to open Board Editor

lib/src/model/common/node.dart, test/model/common/node_test.dart
align implementation with Node.mainline
=> fix: ViewRoot.mainline & ViewBranch.mainline

android/app/src/main/AndroidManifest.xml
Closes #914 and follows up on #221.
=> Disable resizing of app view on Android

lib/src/model/game/game_controller.dart
=> Fix premove autoqueen pref

lib/src/model/challenge/challenge.dart, lib/src/model/challenge/challenge_preferences.dart, lib/src/model/lobby/create_game_service.dart, lib/src/view/game/game_screen.dart, lib/src/view/home/home_tab_screen.dart, lib/src/view/play/create_challenge_screen.dart, test/network/fake_websocket_channel.dart
=> Fix correspondence challenge creation

lib/src/model/lobby/game_seek.dart, lib/src/model/lobby/game_setup_preferences.dart, lib/src/view/play/create_custom_game_screen.dart
=> Remove side choice on creating custom games

lib/src/view/home/home_tab_screen.dart, lib/src/view/puzzle/puzzle_tab_screen.dart, lib/src/view/settings/settings_tab_screen.dart
=> Sync profile activity when accessing profile

ios/Podfile.lock, lib/src/model/analysis/analysis_controller.dart, lib/src/model/board_editor/board_editor_controller.dart, lib/src/model/common/chess960.dart, lib/src/model/game/game_controller.dart, lib/src/model/over_the_board/over_the_board_game_controller.dart, lib/src/view/board_editor/board_editor_menu.dart, lib/src/view/board_editor/board_editor_screen.dart, lib/src/view/correspondence/offline_correspondence_game_screen.dart, lib/src/view/game/game_body.dart, lib/src/view/over_the_board/over_the_board_screen.dart, pubspec.lock, test/view/board_editor/board_editor_screen_test.dart
=> Fix chess960 castling

lib/src/model/analysis/analysis_preferences.dart, lib/src/view/analysis/analysis_settings.dart
=> Allow 0 eval lines

lib/src/model/settings/board_preferences.dart, lib/src/view/board_editor/board_editor_screen.dart, lib/src/view/coordinate_training/coordinate_training_screen.dart, lib/src/view/settings/theme_screen.dart, pubspec.lock, pubspec.yaml, test/test_provider_scope.dart
=> Add a border setting to the board

lib/src/view/game/game_result_dialog.dart
=> Remove eval from game result dialog

lib/src/view/game/game_player.dart, lib/src/view/puzzle/puzzle_feedback_widget.dart, lib/src/widgets/board_table.dart, lib/src/widgets/countdown_clock.dart, test/test_helpers.dart, test/test_provider_scope.dart, test/widgets/board_table_test.dart
=> Fix landscape rendering and board scaling issues

lib/src/view/game/game_player.dart
Noticed this while testing #1159
=> feat: play Sound.lowTime if less than 8 seconds to make first move

lib/src/model/game/game_controller.dart
=> feat: play sound when new game is started

lib/src/model/study/study_controller.dart, lib/src/view/study/study_bottom_bar.dart
Fixes #1174 
[nextChapter.webm](https://github.com/user-attachments/assets/f52d9e4e-1e5e-4739-b476-dd598f6e582e)
=> fix(study): improve UX when loading next chapter

lib/src/model/analysis/analysis_controller.dart, lib/src/model/game/game_controller.dart, lib/src/view/analysis/server_analysis.dart, lib/src/view/game/game_body.dart, test/model/game/game_socket_example_data.dart, test/view/game/game_screen_test.dart
=> Fix correspondence analysis

lib/src/model/analysis/analysis_controller.dart, lib/src/model/analysis/analysis_preferences.dart, lib/src/model/common/eval.dart, lib/src/model/engine/evaluation_service.dart, lib/src/model/engine/uci_protocol.dart, lib/src/model/engine/work.dart, lib/src/model/study/study_controller.dart, lib/src/utils/json.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/analysis/analysis_settings.dart, lib/src/view/analysis/stockfish_settings.dart, lib/src/view/engine/engine_depth.dart, lib/src/view/study/study_screen.dart, lib/src/view/study/study_settings.dart, lib/src/widgets/list.dart, test/model/common/node_test.dart
=> Implement analysis search time

lib/src/view/analysis/analysis_layout.dart, lib/src/view/puzzle/puzzle_screen.dart, lib/src/view/puzzle/puzzle_tab_screen.dart, lib/src/widgets/board_table.dart, lib/src/widgets/bottom_bar.dart, test/widgets/board_table_test.dart
=> Square layout

lib/src/model/study/study.dart, lib/src/model/study/study_controller.dart, lib/src/view/study/study_list_screen.dart, lib/src/view/study/study_screen.dart, lib/src/widgets/adaptive_bottom_sheet.dart, lib/src/widgets/buttons.dart, test/view/study/study_list_screen_test.dart
- also make the study list UI more consistent with the rest of the app
- and improved study chapter menu
=> Implement study like

lib/src/view/study/study_bottom_bar.dart
=> fix(study): make bottom bar back/next consistent with rest of the app

lib/src/model/broadcast/broadcast_game_controller.dart, lib/src/model/common/node.dart, lib/src/utils/duration.dart, lib/src/view/analysis/analysis_layout.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/broadcast/broadcast_game_screen.dart, lib/src/view/game/game_common_widgets.dart
=> Fix broadcast board landscape

lib/src/view/broadcast/broadcast_list_screen.dart, lib/src/view/puzzle/puzzle_history_screen.dart, lib/src/view/study/study_list_screen.dart, lib/src/view/user/game_history_screen.dart, lib/src/view/watch/watch_tab_screen.dart, test/view/broadcast/broadcasts_list_screen_test.dart
- better layout
- uniform pagination scroll behavior
=> Broadcast list screen improvements

lib/src/model/broadcast/broadcast.dart, lib/src/model/broadcast/broadcast_providers.dart, lib/src/model/broadcast/broadcast_repository.dart, lib/src/view/watch/watch_tab_screen.dart, test/model/broadcast/broadcast_repository_test.dart
Close #1221 
[broadcast.webm](https://github.com/user-attachments/assets/6de09321-9a7e-4b16-8e76-89f7cf603ce3)
=> Fix broadcast list that was reloading when scrolling

lib/src/model/analysis/analysis_controller.dart, lib/src/model/broadcast/broadcast_game_controller.dart, lib/src/model/study/study_controller.dart
=> Fix current engine evaluation not in sync with position

lib/src/model/broadcast/broadcast_game_controller.dart, lib/src/model/broadcast/broadcast_round_controller.dart
=> Resync broadcast state on app resume

lib/src/view/broadcast/broadcast_overview_tab.dart
=> Tweak markdown padding on broadcast overview tab

lib/src/model/broadcast/broadcast.dart, lib/src/model/broadcast/broadcast_repository.dart, lib/src/view/broadcast/broadcast_list_screen.dart, lib/src/view/broadcast/broadcast_round_screen.dart
=> Fix null value error on broadcast round start date

test/test_provider_scope.dart
Currently when a Flutter test fails on my computer, it freezes until I send a SIGINT signal.
This commit fixes it.
=> Use the right onError Flutter method for tests

lib/src/view/over_the_board/configure_over_the_board_game.dart
=> Fix typo - oponent

lib/src/view/puzzle/puzzle_screen.dart
=> Make arrow color of puzzles the same as best move on analysis

lib/src/network/socket.dart, test/network/fake_websocket_channel.dart, test/network/socket_test.dart
A new [batch event was added to lila-ws](https://github.com/lichess-org/lila-ws/commit/d0f9785fd6fe08a06d453feda626c0532520a0c3) to handle exceptional broadcasts.
[Here](https://github.com/lichess-org/lila/commit/287ba0b2575035f577b8f8334703592deaed75ed) is the change for the client website.
This pull request does the same for the mobile app.
=> Add socket batch event

lib/src/view/broadcast/broadcast_game_screen.dart
=> Fix broadcast clocks when using flip board

lib/src/model/analysis/analysis_preferences.dart, lib/src/view/analysis/analysis_settings.dart, lib/src/view/analysis/tree_view.dart, lib/src/view/study/study_settings.dart, lib/src/view/study/study_tree_view.dart, lib/src/widgets/pgn.dart, test/view/analysis/analysis_screen_test.dart, test/view/study/study_screen_test.dart
[twoColumn.webm](https://github.com/user-attachments/assets/a730b7cb-b62b-455a-9dce-c56d7862e7a0)
=> feat: two-column tree view

lib/src/model/broadcast/broadcast.dart, lib/src/model/broadcast/broadcast_repository.dart, lib/src/view/broadcast/broadcast_boards_tab.dart, lib/src/view/broadcast/broadcast_game_screen.dart
Close last bug in #1432
Add new game results 1/2-0, 0-0, 0-1/2 for broadcast and refactor code for broadcast results into methods of the `BroadcastResult` enum
=> Add new broadcast game results

lib/src/model/broadcast/broadcast_repository.dart, lib/src/view/broadcast/broadcast_boards_tab.dart
Close first two bugs in #1432
- [Fix clock that have a negative duration](https://github.com/lichess-org/mobile/commit/b679aec189c4c2101c17e4e4036a99465c2017eb)
- [Don't start the clock if a move has not yet been played](https://github.com/lichess-org/mobile/commit/f54087b6aefaeb010692043e2284df6079508b8b)
=> Fix broadcast clock

assets/endgames.json, assets/positions.json, lib/src/model/board_editor/position.dart, lib/src/view/board_editor/board_editor_menu.dart, pubspec.yaml
Hi there, this PR contains a raw implementation of the load position feature. 
-----------
closes #991
=> [Feat] Load position in board editor

lib/src/view/analysis/analysis_layout.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/broadcast/broadcast_game_screen.dart, lib/src/view/study/study_screen.dart, test/view/analysis/analysis_layout_test.dart
Close https://github.com/lichess-org/mobile/issues/1408
The fix done in the PR #1428 could not work. This time it should really be fixed.
=> Fix clock when board is flipped

lib/src/model/analysis/analysis_controller.dart, lib/src/model/broadcast/broadcast_analysis_controller.dart, lib/src/model/engine/evaluation_service.dart, lib/src/model/study/study_controller.dart, lib/src/view/broadcast/broadcast_game_screen.dart, lib/src/view/broadcast/broadcast_game_screen_providers.dart, lib/src/view/engine/engine_depth.dart, lib/src/view/engine/engine_gauge.dart, lib/src/view/engine/engine_lines.dart, lib/src/view/puzzle/puzzle_screen.dart
It should be only reviewed after #1467 as this a follow-up to this PR (only the second commit is new).
=> Implement cloud eval only for broadcast

lib/src/view/analysis/analysis_settings_screen.dart, lib/src/view/broadcast/broadcast_game_settings_screen.dart
Left one is before, right one is after. You can see on the left one the shadows of the nested `ListSection` on top of the other one
=> Tweak analysis settings UI

lib/src/view/user/perf_stats_screen.dart
=> Added colors to user performance page.

lib/src/model/broadcast/broadcast.dart, lib/src/model/broadcast/broadcast_analysis_controller.dart, lib/src/model/broadcast/broadcast_repository.dart, lib/src/view/broadcast/broadcast_boards_tab.dart, lib/src/view/broadcast/broadcast_game_screen.dart, test/view/broadcast/broadcast_round_screen_test.dart
- Rename broadcast BroadcastResult.ongoing because '*' means the game can be new or ongoing
- Use the same condition as the website to check if a game is ongoing
=> Broadcast ongoing game status change

lib/src/model/study/study.dart, lib/src/model/study/study_controller.dart, lib/src/view/study/study_bottom_bar.dart, test/view/study/study_screen_test.dart
This PR show chapter's title in a RichText widget, allowing to proper style chapter indexes. For #1392.
=> Use RichText widget to display study chapters title

lib/src/view/clock/clock_tool_screen.dart, lib/src/widgets/clock.dart
This PR closes https://github.com/lichess-org/mobile/issues/1529
| | | |
|---------|---------|---------|
| ![Screenshot_1741303516](https://github.com/user-attachments/assets/4b050b78-5af3-4fe5-ae7d-bd430ebed59c) | | ![Screenshot_1741304132](https://github.com/user-attachments/assets/03324ee8-b15a-4b6b-a48f-8423fcbeceac) |
=> Fix clock orientation by adding inverted opponent view

lib/src/model/broadcast/broadcast.dart, lib/src/model/broadcast/broadcast_providers.dart, lib/src/model/broadcast/broadcast_repository.dart, lib/src/view/broadcast/broadcast_boards_tab.dart, lib/src/view/broadcast/broadcast_game_screen.dart, lib/src/view/broadcast/broadcast_player_results_screen.dart, lib/src/view/broadcast/broadcast_player_widget.dart, lib/src/view/broadcast/broadcast_players_tab.dart
- Add a composition layer to broadcast player classes so that they all share a same base class
- Refactor `BroadcastPlayerWidget`
- A lot of renaming
=> Rework of broadcast player classes

lib/src/model/broadcast/broadcast.dart, lib/src/model/broadcast/broadcast_repository.dart, lib/src/view/broadcast/broadcast_player_results_screen.dart, lib/src/view/broadcast/broadcast_player_widget.dart, lib/src/view/broadcast/broadcast_players_tab.dart
- Use Dart class destructuring in broadcast player widgets
- Fix a broadcast bug on the broadcast player result screen bug where a row of stats widgets will not be shown if one of the value is null
- Refactor broadcast player result screen
=> Broadcast player Dart destructuring

lib/src/view/analysis/analysis_board.dart, pubspec.lock, pubspec.yaml, test/view/analysis/analysis_screen_test.dart, test/view/engine/test_engine_app.dart
=> Fix best move arrow toggle

lib/src/model/common/id.dart, lib/src/model/tournament/tournament.dart, lib/src/model/tournament/tournament_providers.dart, lib/src/model/tournament/tournament_repository.dart, lib/src/view/play/create_game_options.dart, lib/src/view/tournament/tournament_list_screen.dart, test/view/tournament/tournament_list_screen_test.dart
Layout is copied from the old app for now, we can always improve it later of course
[tournamentlist.webm](https://github.com/user-attachments/assets/7518192e-ce39-4f4c-af8f-70fe49f1129d)
=> feat: tournament list screen

lib/src/model/broadcast/broadcast_round_controller.dart, lib/src/view/broadcast/broadcast_boards_tab.dart
=> Fix broadcast observed games null exception

lib/src/model/account/account_repository.dart, lib/src/view/game/game_body.dart
=> fix: disable chat if account is in kid mode

lib/src/model/puzzle/puzzle_controller.dart, lib/src/model/puzzle/streak_storage.dart, lib/src/view/puzzle/puzzle_tab_screen.dart, test/view/puzzle/puzzle_tab_screen_test.dart
Would be a nice quality of life improvement IMO :)
[streakBadge.webm](https://github.com/user-attachments/assets/1fd434d6-2ede-40d7-ba1b-045f02f9a697)
=> feat: add badge for current streak score in puzzle tab

lib/src/model/clock/chess_clock.dart, test/model/clock/chess_clock_test.dart
Fixes #1626.
This regression was introduced in https://github.com/lichess-org/mobile/pull/1135: The `_checkEmergency()` function was copied [from the old `CountdownClock` widget ](https://github.com/lichess-org/mobile/pull/1135/files#diff-853d63dc997245e585367e4a44390ce8d8d56255c0cc39846723fa2b7bf0d841L99), for which there always was a separate instance per side. The new `ChessClock` class tracks the time of both sides, so we now also need to track the `shouldPlayEmergencySound` (which I renamed to `shouldTriggerEmergencyCallback`, as the class does not actually play sounds anymore since the refactoring) and `nextEmergency` fields separately for each side.
Added a regression tests as well.
=> fix: track emergency state separately for each side in ChessClock

lib/src/model/game/game_controller.dart, lib/src/view/game/game_body.dart, test/view/game/game_screen_test.dart
=> Fix takeback clock bug

lib/src/model/common/eval.dart, lib/src/model/engine/evaluation_mixin.dart, lib/src/model/engine/evaluation_service.dart, lib/src/model/engine/work.dart, lib/src/view/analysis/analysis_board.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/broadcast/broadcast_game_screen.dart, lib/src/view/engine/engine_depth.dart, lib/src/view/study/study_screen.dart, lib/src/view/study/study_settings.dart
=> Deeper analysis

lib/src/widgets/clock.dart
=> Fix: Make opponent's clock red when a player flags (issue #1561)

ios/Podfile.lock, pubspec.lock, pubspec.yaml
Should fix potential lag when playing with sound on android devices.
Closes #1760
=> Upgrade sound effect plugin

lib/src/utils/gestures_exclusion.dart, lib/src/view/game/game_body.dart, lib/src/view/game/game_loading_board.dart, lib/src/view/game/game_screen.dart, lib/src/view/home/home_tab_screen.dart, lib/src/widgets/bottom_bar.dart, test/view/game/game_screen_test.dart
=> Fix board position change when starting a game and Immersive Mode is set

lib/src/widgets/adaptive_choice_picker.dart
=> Fix confirm move menu on iOS

lib/src/theme.dart
close https://github.com/lichess-org/mobile/issues/1681
https://github.com/user-attachments/assets/f96b188e-3416-4698-9e6e-55dac73a0904
=> use FadeForwardsPageTransitionBuilder

lib/src/model/clock/clock_tool_controller.dart, lib/src/view/clock/clock_settings.dart, lib/src/view/clock/clock_tool_screen.dart, lib/src/view/clock/custom_clock_settings.dart
=> Fix clock tool dead zone bug, and simplify starting clock

CONTRIBUTING.md
Adds quotes to links so they filter correctly
=> Fix issue label links in `CONTRIBUTING.md`

lib/src/view/puzzle/puzzle_session_widget.dart
fixes #293
The issue stemmed from the use of `OrientationBuilder`, which surprisingly seems to take the orientation of the parent widget, which can differ from the device orientation.
Since the puzzle session widget is within a board table, there is always enough space for three lines in landscape mode.
=> fix #293, make three lines puzzle session

lib/src/view/analysis/analysis_board.dart
Reverts lichess-org/mobile#1963
=> Revert "fix: immediately hide best move arrows from previous position when making a move in analysis board"

lib/src/model/analysis/analysis_controller.dart, lib/src/model/analysis/forecast.dart, lib/src/model/common/node.dart, lib/src/model/common/uci.dart, lib/src/model/game/game.dart, lib/src/model/game/game_controller.dart, lib/src/model/game/game_repository.dart, lib/src/model/game/playable_game.dart, lib/src/view/analysis/analysis_layout.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/analysis/conditional_premoves.dart, lib/src/view/analysis/tree_view.dart, lib/src/view/correspondence/offline_correspondence_game_screen.dart, lib/src/view/game/game_body.dart, lib/src/widgets/pgn.dart, test/model/analysis/forecast_test.dart, test/model/common/node_test.dart, test/model/common/uci_test.dart, test/model/game/game_socket_events_test.dart, test/view/analysis/analysis_screen_test.dart, test/view/game/game_screen_test.dart
[conditional_premoves.webm](https://github.com/user-attachments/assets/6899ee4c-e676-4542-b040-46e6dc3e25fb)
=> feat: conditional premoves in correspondence matches

lib/src/model/game/game_filter.dart, lib/src/model/game/game_repository.dart, lib/src/model/user/user.dart, lib/src/model/user/user_repository.dart, lib/src/view/user/game_history_screen.dart, lib/src/view/user/user_screen.dart
closes #1872 
Impelements the h2h. The h2h score is shown only when the logged in user played the clicked user already. Clicking on the H2H score opens the Game History screen with the games against the opponent.
<details>
<summary>Video</summary>
[h2h.webm](https://github.com/user-attachments/assets/b142f5aa-664b-4cc2-8970-317815aba419)
</details>
=> add crosstable scores to Userscreen

lib/src/model/tournament/tournament.dart, lib/src/model/tournament/tournament_controller.dart, lib/src/model/tournament/tournament_repository.dart, test/view/tournament/tournament_screen_test.dart
Reverts lichess-org/mobile#1978
=> Revert "fix: switching pages for large tournaments"

lib/src/model/analysis/analysis_controller.dart, lib/src/view/analysis/analysis_screen.dart, lib/src/view/broadcast/broadcast_game_screen.dart
Improves the UI of the analysis board by adding the result to the analysis board and making the names bold, similar to the broadcast screen.
| Before | After |
|--------|-------|
| <img src="https://github.com/user-attachments/assets/91d28392-7bbe-42e9-9dc6-4f1f119d29a8" width="300"/> | <img src="https://github.com/user-attachments/assets/ea1dbc39-ad2e-4916-b6b5-7c3497c37ef8" width="300"/> |
=> Add Result to Analysisboard

ios/Podfile, ios/Podfile.lock, ios/Runner.xcodeproj/project.pbxproj, lib/src/model/message/message.dart, lib/src/model/message/message_repository.dart, lib/src/view/account/account_drawer.dart, pubspec.lock, pubspec.yaml
=> Inbox unread api

lib/src/model/account/account_preferences.dart, lib/src/model/account/account_repository.dart, lib/src/view/settings/account_preferences_screen.dart
<details>
<summary>Screenshot</summary>
</details>
- I tested the changes using Gitpod.
- The server-side changes are included in the following pull request:
https://github.com/lichess-org/lila/pull/17938
=> add message section privacy prefs

lib/src/view/board_editor/board_editor_screen.dart, lib/src/view/play/create_challenge_bottom_sheet.dart, lib/src/view/user/search_screen.dart
=> Add: Challenge from custom position (using board editor)

lib/src/app_links.dart, lib/src/view/chat/chat_screen.dart, lib/src/view/message/conversation_screen.dart, lib/src/view/user/user_context_menu.dart, lib/src/view/user/user_profile.dart
Also open lichess links directly in the app.
Closes #2070 
Closes #2019
=> Recognize links in chat and conversation screens

android/fastlane/Fastfile, android/fastlane/add-debug-symbols.sh
Retry https://github.com/lichess-org/mobile/pull/1983 reverted in https://github.com/lichess-org/mobile/pull/2004.
=> Try again to upload the debug symbols of libapp.so to the Play Console.

lib/src/model/chat/chat_controller.dart, lib/src/model/game/game_repository.dart, lib/src/view/chat/chat_context_menu.dart, lib/src/view/chat/chat_screen.dart, lib/src/view/message/conversation_screen.dart
On game chat copy and report are available
On conversation (PM) screen, only copy.
Resolves #1806 
Resolves #2072
=> Add chat context menu with copy and report

build.yaml, lib/src/model/challenge/challenge_service.dart, lib/src/model/correspondence/correspondence_service.dart, lib/src/model/lobby/create_game_service.dart, lib/src/quick_actions.dart, lib/src/view/game/game_body.dart, lib/src/view/game/game_common_widgets.dart, lib/src/view/game/game_loading_board.dart, lib/src/view/game/game_screen.dart, lib/src/view/game/game_screen_providers.dart, lib/src/view/home/home_tab_screen.dart, lib/src/view/play/challenge_odd_bots_screen.dart, lib/src/view/play/correspondence_challenges_screen.dart, lib/src/view/play/create_challenge_bottom_sheet.dart, lib/src/view/play/create_game_widget.dart, lib/src/view/play/ongoing_games_screen.dart, lib/src/view/play/quick_game_matrix.dart, lib/src/view/tournament/tournament_screen.dart, lib/src/view/user/challenge_requests_screen.dart, test/view/game/game_screen_test.dart
Tried to understand the code because I wanted to implement the "Play with a friend feature" (aka generating challenge links), but I found the code hard to follow in some places.
I think the union types help to improve readability and better express some of the invariants.
=> refactor: use @freezed unions to improve readability of GameScreen code

lib/src/model/puzzle/puzzle_controller.dart, lib/src/model/puzzle/puzzle_service.dart, lib/src/view/puzzle/puzzle_history_screen.dart, lib/src/view/puzzle/puzzle_screen.dart, test/view/puzzle/puzzle_screen_test.dart
=> Don't send puzzle result when reviewing storm

lib/src/model/study/study.dart, lib/src/view/study/study_screen.dart, test/model/study/study_repository_test.dart, test/view/study/study_screen_test.dart
=> feat: show a list of study members

lib/src/view/settings/http_log_screen.dart
=> fix: correct a typo in the HTTP logs screen title for consistency

lib/src/model/game/game_controller.dart, lib/src/view/game/game_body.dart
=> Fix correspondence not receiving push when app is just put in background
